"use client";

import { useState } from "react";
import { Sparkles, Copy, Check } from "lucide-react";
import { runProviderIntelligence } from "@/src/lib/ai-client";
import type { IntelligenceTaskType } from "@/src/lib/intelligence/tasks";
import { Button } from "@/src/components/ui/Button";
import { DownloadButton } from "@/src/components/ui/DownloadButton";
import { downloadText, safeFileName } from "@/src/lib/download";

/**
 * One-click Gemini generation for a studio: sends the live project context,
 * shows the real model output, and lets the user copy or download it.
 */
export function GeminiAssist({
  task,
  title,
  blurb,
  context,
  actionLabel = "Generate with Gemini",
  disabledReason,
}: {
  task: IntelligenceTaskType;
  title: string;
  blurb: string;
  context: Record<string, unknown>;
  actionLabel?: string;
  disabledReason?: string;
}) {
  const [busy, setBusy] = useState(false);
  const [text, setText] = useState("");
  const [model, setModel] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  async function run() {
    setBusy(true);
    setError("");
    const outcome = await runProviderIntelligence(task, context);
    setBusy(false);
    if (outcome.ok) {
      setText(outcome.data.text);
      setModel(outcome.data.model);
    } else setError(outcome.message);
  }

  return (
    <section className="space-y-3 rounded-xl border border-primary/30 bg-primary/5 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <h3 className="flex items-center gap-1.5 text-sm font-semibold">
            <Sparkles className="size-4 text-primary" aria-hidden="true" /> {title}
          </h3>
          <p className="mt-0.5 text-xs text-muted-text">{disabledReason || blurb}</p>
        </div>
        <Button size="sm" loading={busy} disabled={Boolean(disabledReason)} onClick={() => void run()}>
          <Sparkles className="size-3.5" aria-hidden="true" /> {text ? "Regenerate" : actionLabel}
        </Button>
      </div>
      {error && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
      {text && (
        <div className="ui-panel space-y-2">
          <pre className="max-h-[28rem] overflow-auto whitespace-pre-wrap break-words rounded-lg border border-border bg-surface p-3 font-sans text-sm leading-relaxed">{text}</pre>
          <div className="flex flex-wrap items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={() => {
                void navigator.clipboard?.writeText(text);
                setCopied(true);
                setTimeout(() => setCopied(false), 1500);
              }}
            >
              {copied ? <Check className="size-3.5" aria-hidden="true" /> : <Copy className="size-3.5" aria-hidden="true" />} {copied ? "Copied" : "Copy"}
            </Button>
            <DownloadButton onDownload={() => downloadText(text, safeFileName(title, "md"), "text/markdown")} />
            {model && <span className="text-[11px] text-muted-text">Generated by {model}</span>}
          </div>
        </div>
      )}
    </section>
  );
}
